#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController::index

ToDoList:
    path: /todo
    controller: App\Controller\TodoController::list

viewTodoItem:
    path: /todo/item/{itemId}
    controller: App\Controller\TodoController::viewItem

deleteTodoItem:
    path: /todo/deleteItem/{itemId}
    controller: App\Controller\TodoController::deleteItem
    methods: [DELETE]

toggleTodoItemDone:
    path: /todo/item/{itemId}/toggleIsDone
    controller: App\Controller\TodoController::toggleItemIsDone
    methods: [POST]

login:
    path: /login

logout:
    path: /logout
